[src]
exclude = ["algorithms/code/other/banking", "algorithms/code/other/mac", "algorithms/code/other/federated_machine_learning"]

[rules]
unused-type-ignore-comment = "ignore"
unused-ignore-comment = "ignore"
