@startuml architecture-current

node "Shared Services" as SHARED {
    component "Email Service\n(Spring Boot)\nEC2 Instance" as EMAIL #D4EDDA
    component "Push Notifications Service\n(Spring Boot)\nEC2 Instance" as PUSH #D4EDDA
    component "File Storage Service\n(Spring Boot)\nEC2 Instance (500 GiB)" as FILES #D4EDDA
    EMAIL -[hidden]right- PUSH
    PUSH -[hidden]right- FILES
}

node "EC2 Instance 1" as T1 {
    component "Web Application\n(Angular.js)" as W1 #F8D7DA
    component "Backend API\n(Spring Boot)" as A1 #D4EDDA
    database "Database\n(postgresql)" as D1 #CFE2F3
    W1 -[hidden]right- A1
    A1 -[hidden]right- D1
}

node "EC2 Instance 2" as T2 {
    component "Web Application\n(Angular.js)" as W2 #F8D7DA
    component "Backend API\n(Spring Boot)" as A2 #D4EDDA
    database "Database\n(postgresql)" as D2 #CFE2F3
    W2 -[hidden]right- A2
    A2 -[hidden]right- D2
}

node "EC2 Instance X" as TX {
    component "Web Application\n(Angular.js)" as WX #F8D7DA
    component "Backend API\n(Spring Boot)" as AX #D4EDDA
    database "Database\n(postgresql)" as DX #CFE2F3
    WX -[hidden]right- AX
    AX -[hidden]right- DX
}

T1 -up-> SHARED : Service invocation
T2 -up-> SHARED : Service invocation
TX -up-> SHARED : Service invocation

rectangle "Tenant 1 clients" as CL1 {
    node "<&phone{scale=1.5}> Client 1" as C1A
    node "<&laptop{scale=1.5}> Client 2" as C1B
    node "<&monitor{scale=1.5}> Client X" as C1C
    C1A -[hidden]right- C1B
    C1B -[hidden]right- C1C
}

rectangle "Tenant 2 clients" as CL2 {
    node "<&phone{scale=1.5}> Client 1" as C2A
    node "<&laptop{scale=1.5}> Client 2" as C2B
    node "<&monitor{scale=1.5}> Client X" as C2C
    C2A -[hidden]right- C2B
    C2B -[hidden]right- C2C
}

rectangle "Tenant X clients" as CLX {
    node "<&phone{scale=1.5}> Client 1" as CXA
    node "<&laptop{scale=1.5}> Client 2" as CXB
    node "<&monitor{scale=1.5}> Client X" as CXC
    CXA -[hidden]right- CXB
    CXB -[hidden]right- CXC
}

CL1 -up-> T1 : http://api-1.company.com
CL2 -up-> T2 : http://api-2.company.com
CLX -up-> TX : http://api-X.company.com

@enduml
