import re

TASK_ID_PATTERN = r"^[0-9a-f]{64}$"
ALLOWED_BYTES = frozenset(b"0123456789abcdefABCDEF\n")
HEXADECIMAL_DIGITS = 12
OUI_PREFIX = b"000FAC"
STANDARD_SEPARATOR = b":"
OCTET_DIGITS = 2
MAC_ADDRESS = re.compile(
    rb"%s[0-9A-F]{%d}" % (OUI_PREFIX, HEXADECIMAL_DIGITS - len(OUI_PREFIX)),
    re.IGNORECASE,
)
MAX_CANDIDATE_LENGTH = HEXADECIMAL_DIGITS
